name: 02 - workflow events

on: 
    push:
    pull_request:
    schedule:
            - cron: '*/5 * * * *'  # every day at midnight UTC
jobs: 
    echo:
        runs-on: ubuntu-latest
        steps:
            - name: Show the triggere
              run: echo "I've been triggered by a(n) ${{ github.event_name }} event."