name: 07 - Using Expressions

run-name: 07 - Using Expressions | DEBUG - ${{ inputs.debug && 'ON' || 'OFF' }}

on: 
    push:
    workflow_dispatch:
        inputs:
            debug:
                type: boolean
                default: false
jobs:
    expressions:
        runs-on: ubuntu-latest
        steps:
           - name: '[debug] Print start-up data'
             if: ${{ inputs.debug }}   
             run: |
                echo "Debug mode is enabled"
                echo "Event name: ${{ github.event_name }}"
                echo "Ref: ${{ github.ref }}"
                echo "SHA: ${{ github.sha }}"
                echo "Repository: ${{ github.repository }}"
                echo "Actor: ${{ github.actor }}"
                echo "Workflow: ${{ github.workflow }}"
                echo "Job: ${{ github.job }}"
                echo "Run ID: ${{ github.run_id }}"
                echo "Run Number: ${{ github.run_number }}"
                echo "Event Path: ${{ github.event_path }}"
                echo "Workspace: ${{ github.workspace }}"
                echo "Action: ${{ github.action }}"
                echo "Head Ref: ${{ github.head_ref }}"
                echo "Base Ref: ${{ github.base_ref }}" 
                echo "Runner OS: ${{ runner.os }}"

           - name: '[debug] Print when triggered from main branch'
             if: ${{ inputs.debug && github.ref_name== 'refs/heads/`main' }}
             run: echo "I was triggered from the main branch"

           - name: Greeting
             run: |
                echo "Hello, Hello!"