name: 10 - Controlling the Exec Workflow
on:
    push:
    workflow_dispatch:
        inputs:
            pass-unit-tests:
                type: boolean
                description: 'Set to true to run tests'
                default: true
jobs:
    lint-build:
        runs-on: ubuntu-latest
        continue-on-error: true
        steps:
            - name: Lint and Build
              run: echo "Starting lint and build process..."
    unit-tests:
        runs-on: ubuntu-latest
        steps:
            - name: Running Unit Tests
              run: echo "Running unit tests..."

            - name: Failing Unit Tests
              if: ${{ !inputs.pass-unit-tests }}
              run: |
                echo "Simulating failing unit tests"
                exit 1
    deploy-non-prod:
        runs-on: ubuntu-latest
        needs:
            - lint-build
            - unit-tests
        if: ${{ inputs.pass-unit-tests }}
        steps:
            - name: Deploy to Non-Prod
              run: echo "Deploying to non-production environment..."
    e2e-tests:
        runs-on: ubuntu-latest
        needs: deploy-non-prod
        steps:
            - name: E2E Testing
              run: echo "Running E2E tests..."

    load-tests:
        runs-on: ubuntu-latest
        needs: deploy-non-prod
        steps:
            - name: Load Testing
              run: echo "Running load tests..."

    deploy-prod:
        runs-on: ubuntu-latest
        needs:
            - e2e-tests
            - load-tests
        steps:
            - name: Deploy Application
              run: echo "Deploying application..."     
        