name: 14 - Working with Artifacts

on: 
    workflow_dispatch:

jobs:
    test-build:
        runs-on: ubuntu-latest
        defaults:
          run:
            working-directory: 14-cashing/react-app
        steps:
            - name: Checkout repository
              uses: actions/checkout@v3
            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                node-version: '20.x'
            - name: Downaload cached dependencies
              uses: actions/cache@v3
              id: cache-node-modules
              with:
                path: 14-cashing/react-app
                key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
            - name: Install dependencies
              if: ${{ steps.cache-node-modules.outputs.cache-hit != 'true'}}
              run: npm ci
            - name: Unit tests
              run: npm test
            - name: Build project   
              run: npm run build
            - name: upload-artifact
              uses: actions/upload-artifact@v4
              with:
                name: app
                path: 14-cashing/react-app/build
    deploy:
        runs-on: ubuntu-latest
        needs: test-build
        steps:
            - name: Download artifact
              uses: actions/download-artifact@v4
              with:
                name: app
                path: 14-cashing/react-app/build
            - name: Show folder structure
              run: ls -R 