name: 15- Exploring Matrices

on: 
    workflow_dispatch:


jobs:
    backward-compatibility:
        runs-on: ubuntu-latest
        strategy:
            fail-fast: true
            matrix:
                node-version: [16.x, 18.x, 19.x, 20.x]
                os: [ubuntu-latest, windows-latest, macos-latest]
                include:
                - node-version: 15.x
                  os: ubuntu-latest
                - node-version: 21.x
                  os: ubuntu-latest
                  tag: experimental
                

        steps:
            - name: Set up Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v3
              with:
                node-version: ${{ matrix.node-version }}
            - name: fail if experimental
                if matrix.tag == 'experimental'
              run: |
                echo "This is an experimental configuration. Failing the job."
                exit 1
            - name: Check Node.js version
              run: node -v
            - name: Check OS
              run: |
                echo "Running on ${{ matrix.os }} and Node.js version ${{ matrix.node-version }}"
                sleep 10
            - name:  UPload results
              run: echo "Results uploaded for Node.js ${{ matrix.node-version }} on ${{ matrix.os }}"
             
    test-multiple-versions:
        name: "${{ matrix.os }} - Node.js ${{ matrix.node-version }} - Shape: ${{ matrix.shape }} - Color: ${{ matrix.color }} - Size: ${{ matrix.size }} - Opacity: ${{ matrix.opacity}}"
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [16.x, 18.x, 20.x]
                os: [ubuntu-latest, windows-latest]
                shape: [circle, square]
                color: [red, green, blue]
                size: [small, medium, large]
                include:
                    - shape: sqquare
                      opacity: 100
                    - color: blue
                      opacity: 75
                    - opacity: 50
        steps:
            - name: Dummy step to show matrix values
              run: |
                echo "Running on ${{ matrix.os }} with Node.js ${{ matrix.node-version }}"
                echo "Shape: ${{ matrix.shape }}, Color: ${{ matrix.color }}, Size: ${{ matrix.size }}, Opacity: ${{ matrix.opacity }}"
              
            